---
version: "2"

linters:
  enable:
    - revive

  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - allowRegex: "^_"
