---
name: Build README

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: Roee Shapira
          message: "Built new readme file"
          add: "--update"
