---
name: Build README

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
      - name: Install deps
        run: go mod tidy
      - name: Build
        run: go run .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Roee
          message: "Update readme file"
          add: "--update"
