---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v6

  build:
    name: Build `README.md`
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: "go.sum"
          go-version-file: "go.mod"
      - name: Install deps
        run: go mod tidy
      - name: Build
        run: go run .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update `README.md`"
          add: "README.md"
